---
name: node CI
on: push
jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: prepare
        run: npm ci
      - name: check
        run: |
          npm run lint
          npm run test
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: prepare
        run: npm ci
      - name: collect coverage
        run: npm run coverage
      - name: scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
